import { Card, Tabs } from "@mantine/core";
import AdminImportPanel from "./AdminImportPanel";
import AdminOwnerPanel from "./AdminOwnerPanel";
import AdminVersionsPanel from "./AdminVersionsPanel";
import AdminApplicationsPanel from "./AdminApplicationsPanel";
import AdminSafetyPanel from "./AdminSafetyPanel";
import AdminCvBuilderPanel from "./AdminCvBuilderPanel";
import AdminProfilePanel from "./AdminProfilePanel";
import AdminTimelinePanel from "./AdminTimelinePanel";
import AdminProjectsPanel from "./AdminProjectsPanel";

export default function AdminMainTabs({ controller }) {
  const {
    adminActiveTab,
    setAdminActiveTab,
    jsonImportFile,
    setJsonImportFile,
    importJsonFromFile,
    loading,
    jsonImportText,
    setJsonImportText,
    importJsonFromText,
    jsonImportSummary,
    ownerForm,
    updateOwnerForm,
    addOwnerContact,
    updateOwnerContact,
    removeOwnerContact,
    updateOwner,
    selectedOwnerId,
    createOwner,
    versionForm,
    updateVersionForm,
    versions,
    cloneSourceVersionId,
    setCloneSourceVersionId,
    cloneVersion,
    createVersion,
    updateVersionMetadata,
    selectedVersionId,
    selectVersion,
    activateVersionWithValidation,
    applicationsDashboard,
    offerAnalysis,
    applyOfferCommandsToCv,
    smartAnalysis,
    selectedLetterVariantId,
    selectedSmartCvProposal,
    selectedSmartCvCommands,
    loadLetterTemplates,
    runSmartApplicationAnalysis,
    exportSmartApplicationPack,
    selectedApplicationId,
    setCommandTraceOpened,
    smartPackUrl,
    letterTemplates,
    selectedSmartCommandKeys,
    getSmartCommandKey,
    formatCvCommand,
    setSelectedSmartCommandKeys,
    setProposalCommandsSelection,
    countSelectedProposalCommands,
    applySmartCvProposal,
    selectedCvProposalId,
    setSelectedCvProposalId,
    setSelectedLetterVariantId,
    useSmartLetterVariant,
    loadApplications,
    resetApplicationForm,
    applications,
    selectApplication,
    applicationForm,
    updateApplicationForm,
    cvVariants,
    analyzeCurrentOffer,
    saveApplication,
    deleteApplication,
    markApplicationStatus,
    previewCoverLetter,
    saveCoverLetter,
    exportApplicationPackage,
    coverLetterPreviewUrl,
    coverLetterLogs,
    coverLetterWarnings,
    applicationZipUrl,
    portfolioHealthReport,
    publishValidationReport,
    runPortfolioHealthCheck,
    validatePortfolioBeforePublish,
    selectedVersion,
    portfolioBackupUrl,
    portfolioBackupJson,
    exportPortfolioBackupZip,
    downloadTextFile,
    portfolioRestoreLabel,
    setPortfolioRestoreLabel,
    restorePortfolioBackup,
    portfolioRestoreText,
    setPortfolioRestoreText,
    cvDocument,
    cvSelectedItems,
    updateCvProfileField,
    importCvProfilePhoto,
    getCvDragProps,
    toggleCvItem,
    moveCvEditorItem,
    moveCvEditorItemTo,
    duplicateCvItem,
    removeCvItem,
    updateCvItem,
    updateCvItemCsv,
    importCvEducationLogo,
    cvSelectedSection,
    setCvSelectedSection,
    addCvItem,
    sortCvItems,
    cvActiveEditorTab,
    setCvActiveEditorTab,
    toggleCvSection,
    updateCvSettingsField,
    cvQualitySummary,
    cvTemplateLocked,
    updateTemplateLock,
    toggleReduceCvDescriptions,
    updateCvSectionColumn,
    runCvQualityCheck,
    runBackendCvQualityCheck,
    cvVariantName,
    setCvVariantName,
    selectedCvVariantId,
    setSelectedCvVariantId,
    createCvVariantSnapshot,
    saveCurrentCvVariant,
    loadCvVariant,
    deleteCvVariant,
    compareCvVariant,
    cvDiffReport,
    cvPresetName,
    setCvPresetName,
    saveCvCommandPreset,
    cvCommandPresets,
    applyCvCommandPreset,
    cvOfferText,
    setCvOfferText,
    analyzeCvOffer,
    cvOfferAnalysis,
    applyCvTargetPreset,
    applyOfferRecommendations,
    compactCvOnOnePage,
    adjustCvSpacing,
    resetCvEditorFromData,
    smartCompactAndPreview,
    startAsyncCvPreview,
    exportCvReproducibleZip,
    generateLatexFromCvDocument,
    generateCvLatexSource,
    previewGeneratedCv,
    saveGeneratedCvToVersion,
    cvLatexSource,
    setCvLatexSource,
    cvManualLatexDirty,
    setCvManualLatexDirty,
    cvCompileStatusLabel,
    cvCompileStatusColor,
    cvCompileWarnings,
    cvAsyncJob,
    cvCurrentPdfUrl,
    cvExportZipUrl,
    cvRegressionReport,
    setCvRegressionReport,
    cvCanUndo,
    undoCvCommand,
    cvCanRedo,
    redoCvCommand,
    cvEditorState,
    cvCompileLogs,
    profileFiles,
    setProfileFiles,
    profileForm,
    updateProfileForm,
    saveProfile,
    timelineForm,
    updateTimelineForm,
    experienceCategories,
    experienceForm,
    updateExperienceForm,
    experienceFiles,
    setExperienceFiles,
    experiences,
    experienceMode,
    selectedExperienceIndex,
    addExperienceLocally,
    updateExperienceLocally,
    removeExperience,
    duplicateExperience,
    selectExperience,
    resetExperienceForm,
    moveExperience,
    saveTimeline,
    projects,
    projectMode,
    selectedProject,
    selectedProjectId,
    projectFiles,
    setProjectFiles,
    projectForm,
    updateProjectForm,
    projectStatuses,
    getProjectId,
    selectProject,
    resetProjectForm,
    hydrateProjectForm,
    setProjectMode,
    setSelectedProjectId,
    setProjectForm,
    emptyProjectForm,
    emptyProjectFiles,
    addProject,
    updateProject,
    deleteProject,
  } = controller;

  return (
    <Card shadow="sm" padding="xl" radius="xl" withBorder className="admin-tabs-card">
      <Tabs value={adminActiveTab} onChange={(value) => setAdminActiveTab(value ?? "version")} variant="outline" radius="md" className="admin-tabs">
        <Tabs.List>
          <Tabs.Tab value="import">Import JSON</Tabs.Tab>
          <Tabs.Tab value="owner">Profil principal</Tabs.Tab>
          <Tabs.Tab value="version">Versions</Tabs.Tab>
          <Tabs.Tab value="safety">Santé & backup</Tabs.Tab>
          <Tabs.Tab value="applications">Candidatures</Tabs.Tab>
          <Tabs.Tab value="profile">Profil & fichiers</Tabs.Tab>
          <Tabs.Tab value="cv">CV Builder</Tabs.Tab>
          <Tabs.Tab value="timeline">Timeline</Tabs.Tab>
          <Tabs.Tab value="project">Projets</Tabs.Tab>
        </Tabs.List>

        <AdminImportPanel
          jsonImportFile={jsonImportFile}
          setJsonImportFile={setJsonImportFile}
          importJsonFromFile={importJsonFromFile}
          loading={loading}
          jsonImportText={jsonImportText}
          setJsonImportText={setJsonImportText}
          importJsonFromText={importJsonFromText}
          jsonImportSummary={jsonImportSummary}
        />
        <AdminOwnerPanel
          ownerForm={ownerForm}
          updateOwnerForm={updateOwnerForm}
          addOwnerContact={addOwnerContact}
          updateOwnerContact={updateOwnerContact}
          removeOwnerContact={removeOwnerContact}
          updateOwner={updateOwner}
          loading={loading}
          selectedOwnerId={selectedOwnerId}
          createOwner={createOwner}
        />
        <AdminVersionsPanel
          versionForm={versionForm}
          updateVersionForm={updateVersionForm}
          versions={versions}
          cloneSourceVersionId={cloneSourceVersionId}
          setCloneSourceVersionId={setCloneSourceVersionId}
          cloneVersion={cloneVersion}
          selectedOwnerId={selectedOwnerId}
          createVersion={createVersion}
          updateVersionMetadata={updateVersionMetadata}
          selectedVersionId={selectedVersionId}
          selectVersion={selectVersion}
          activateVersionWithValidation={activateVersionWithValidation}
        />
        <AdminApplicationsPanel
          applicationsDashboard={applicationsDashboard}
          offerAnalysis={offerAnalysis}
          applyOfferCommandsToCv={applyOfferCommandsToCv}
          smartAnalysis={smartAnalysis}
          selectedLetterVariantId={selectedLetterVariantId}
          selectedSmartCvProposal={selectedSmartCvProposal}
          selectedSmartCvCommands={selectedSmartCvCommands}
          loadLetterTemplates={loadLetterTemplates}
          runSmartApplicationAnalysis={runSmartApplicationAnalysis}
          exportSmartApplicationPack={exportSmartApplicationPack}
          selectedOwnerId={selectedOwnerId}
          selectedApplicationId={selectedApplicationId}
          setCommandTraceOpened={setCommandTraceOpened}
          smartPackUrl={smartPackUrl}
          letterTemplates={letterTemplates}
          selectedSmartCommandKeys={selectedSmartCommandKeys}
          getSmartCommandKey={getSmartCommandKey}
          formatCvCommand={formatCvCommand}
          setSelectedSmartCommandKeys={setSelectedSmartCommandKeys}
          setProposalCommandsSelection={setProposalCommandsSelection}
          countSelectedProposalCommands={countSelectedProposalCommands}
          applySmartCvProposal={applySmartCvProposal}
          selectedCvProposalId={selectedCvProposalId}
          setSelectedCvProposalId={setSelectedCvProposalId}
          setSelectedLetterVariantId={setSelectedLetterVariantId}
          applySmartLetterVariant={useSmartLetterVariant}
          loadApplications={loadApplications}
          resetApplicationForm={resetApplicationForm}
          applications={applications}
          selectApplication={selectApplication}
          applicationForm={applicationForm}
          updateApplicationForm={updateApplicationForm}
          versions={versions}
          selectedVersionId={selectedVersionId}
          cvVariants={cvVariants}
          analyzeCurrentOffer={analyzeCurrentOffer}
          saveApplication={saveApplication}
          deleteApplication={deleteApplication}
          markApplicationStatus={markApplicationStatus}
          previewCoverLetter={previewCoverLetter}
          saveCoverLetter={saveCoverLetter}
          exportApplicationPackage={exportApplicationPackage}
          coverLetterPreviewUrl={coverLetterPreviewUrl}
          coverLetterLogs={coverLetterLogs}
          coverLetterWarnings={coverLetterWarnings}
          applicationZipUrl={applicationZipUrl}
        />
        <AdminSafetyPanel
          portfolioHealthReport={portfolioHealthReport}
          publishValidationReport={publishValidationReport}
          runPortfolioHealthCheck={runPortfolioHealthCheck}
          validatePortfolioBeforePublish={validatePortfolioBeforePublish}
          activateVersionWithValidation={activateVersionWithValidation}
          selectedOwnerId={selectedOwnerId}
          selectedVersionId={selectedVersionId}
          selectedVersion={selectedVersion}
          portfolioBackupUrl={portfolioBackupUrl}
          portfolioBackupJson={portfolioBackupJson}
          exportPortfolioBackupZip={exportPortfolioBackupZip}
          downloadTextFile={downloadTextFile}
          portfolioRestoreLabel={portfolioRestoreLabel}
          setPortfolioRestoreLabel={setPortfolioRestoreLabel}
          restorePortfolioBackup={restorePortfolioBackup}
          portfolioRestoreText={portfolioRestoreText}
          setPortfolioRestoreText={setPortfolioRestoreText}
        />
        <AdminCvBuilderPanel
          cvDocument={cvDocument}
          cvSelectedItems={cvSelectedItems}
          updateCvProfileField={updateCvProfileField}
          importCvProfilePhoto={importCvProfilePhoto}
          getCvDragProps={getCvDragProps}
          toggleCvItem={toggleCvItem}
          moveCvEditorItem={moveCvEditorItem}
          moveCvEditorItemTo={moveCvEditorItemTo}
          duplicateCvItem={duplicateCvItem}
          removeCvItem={removeCvItem}
          updateCvItem={updateCvItem}
          updateCvItemCsv={updateCvItemCsv}
          importCvEducationLogo={importCvEducationLogo}
          cvSelectedSection={cvSelectedSection}
          setCvSelectedSection={setCvSelectedSection}
          addCvItem={addCvItem}
          sortCvItems={sortCvItems}
          cvActiveEditorTab={cvActiveEditorTab}
          setCvActiveEditorTab={setCvActiveEditorTab}
          toggleCvSection={toggleCvSection}
          updateCvSettingsField={updateCvSettingsField}
          cvQualitySummary={cvQualitySummary}
          cvTemplateLocked={cvTemplateLocked}
          updateTemplateLock={updateTemplateLock}
          toggleReduceCvDescriptions={toggleReduceCvDescriptions}
          updateCvSectionColumn={updateCvSectionColumn}
          runCvQualityCheck={runCvQualityCheck}
          runBackendCvQualityCheck={runBackendCvQualityCheck}
          cvVariantName={cvVariantName}
          setCvVariantName={setCvVariantName}
          cvVariants={cvVariants}
          selectedCvVariantId={selectedCvVariantId}
          setSelectedCvVariantId={setSelectedCvVariantId}
          createCvVariantSnapshot={createCvVariantSnapshot}
          saveCurrentCvVariant={saveCurrentCvVariant}
          loadCvVariant={loadCvVariant}
          deleteCvVariant={deleteCvVariant}
          compareCvVariant={compareCvVariant}
          cvDiffReport={cvDiffReport}
          cvPresetName={cvPresetName}
          setCvPresetName={setCvPresetName}
          saveCvCommandPreset={saveCvCommandPreset}
          cvCommandPresets={cvCommandPresets}
          applyCvCommandPreset={applyCvCommandPreset}
          cvOfferText={cvOfferText}
          setCvOfferText={setCvOfferText}
          analyzeCvOffer={analyzeCvOffer}
          cvOfferAnalysis={cvOfferAnalysis}
          applyCvTargetPreset={applyCvTargetPreset}
          applyOfferRecommendations={applyOfferRecommendations}
          compactCvOnOnePage={compactCvOnOnePage}
          adjustCvSpacing={adjustCvSpacing}
          resetCvEditorFromData={resetCvEditorFromData}
          smartCompactAndPreview={smartCompactAndPreview}
          startAsyncCvPreview={startAsyncCvPreview}
          exportCvReproducibleZip={exportCvReproducibleZip}
          generateLatexFromCvDocument={generateLatexFromCvDocument}
          generateCvLatexSource={generateCvLatexSource}
          previewGeneratedCv={previewGeneratedCv}
          saveGeneratedCvToVersion={saveGeneratedCvToVersion}
          selectedOwnerId={selectedOwnerId}
          selectedVersionId={selectedVersionId}
          cvLatexSource={cvLatexSource}
          setCvLatexSource={setCvLatexSource}
          cvManualLatexDirty={cvManualLatexDirty}
          setCvManualLatexDirty={setCvManualLatexDirty}
          cvCompileStatusLabel={cvCompileStatusLabel}
          cvCompileStatusColor={cvCompileStatusColor}
          cvCompileWarnings={cvCompileWarnings}
          cvAsyncJob={cvAsyncJob}
          cvCurrentPdfUrl={cvCurrentPdfUrl}
          cvExportZipUrl={cvExportZipUrl}
          cvRegressionReport={cvRegressionReport}
          setCvRegressionReport={setCvRegressionReport}
          cvCanUndo={cvCanUndo}
          undoCvCommand={undoCvCommand}
          cvCanRedo={cvCanRedo}
          redoCvCommand={redoCvCommand}
          cvEditorState={cvEditorState}
          cvCompileLogs={cvCompileLogs}
        />
        <Tabs.Panel value="profile" pt="lg">
          <AdminProfilePanel
            profileFiles={profileFiles}
            setProfileFiles={setProfileFiles}
            profileForm={profileForm}
            updateProfileForm={updateProfileForm}
            saveProfile={saveProfile}
            selectedOwnerId={selectedOwnerId}
            selectedVersionId={selectedVersionId}
          />
        </Tabs.Panel>

        <Tabs.Panel value="timeline" pt="lg">
          <AdminTimelinePanel
            timelineForm={timelineForm}
            updateTimelineForm={updateTimelineForm}
            experienceCategories={experienceCategories}
            experienceForm={experienceForm}
            updateExperienceForm={updateExperienceForm}
            experienceFiles={experienceFiles}
            setExperienceFiles={setExperienceFiles}
            experiences={experiences}
            experienceMode={experienceMode}
            selectedExperienceIndex={selectedExperienceIndex}
            selectedOwnerId={selectedOwnerId}
            selectedVersionId={selectedVersionId}
            addExperienceLocally={addExperienceLocally}
            updateExperienceLocally={updateExperienceLocally}
            removeExperience={removeExperience}
            selectExperience={selectExperience}
            resetExperienceForm={resetExperienceForm}
            duplicateExperience={duplicateExperience}
            moveExperience={moveExperience}
            saveTimeline={saveTimeline}
          />
        </Tabs.Panel>

        <Tabs.Panel value="project" pt="lg">
          <AdminProjectsPanel
            projects={projects}
            projectMode={projectMode}
            selectedProject={selectedProject}
            selectedProjectId={selectedProjectId}
            selectedOwnerId={selectedOwnerId}
            selectedVersionId={selectedVersionId}
            projectFiles={projectFiles}
            setProjectFiles={setProjectFiles}
            projectForm={projectForm}
            updateProjectForm={updateProjectForm}
            projectStatuses={projectStatuses}
            getProjectId={getProjectId}
            selectProject={selectProject}
            resetProjectForm={resetProjectForm}
            hydrateProjectForm={hydrateProjectForm}
            setProjectMode={setProjectMode}
            setSelectedProjectId={setSelectedProjectId}
            setProjectForm={setProjectForm}
            emptyProjectForm={emptyProjectForm}
            emptyProjectFiles={emptyProjectFiles}
            addProject={addProject}
            updateProject={updateProject}
            deleteProject={deleteProject}
          />
        </Tabs.Panel>
      </Tabs>
    </Card>
  );
}
